### ISSUE TITLE
Missing infura project id information

### ISSUE THREAD

**Issue by AnaLoznianu** [oceanprotocol/predict-eth#72]
When trying to upload predictions to Polygon, I got this error:
`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 4, in create_ocean_instance
  File "/Users/ana/Desktop/project/venv/lib/python3.8/site-packages/enforce_typing/decorator.py", line 29, in wrapper
    return func(*args, **kwargs)
  File "/Users/ana/Desktop/project/venv/lib/python3.8/site-packages/ocean_lib/web3_internal/utils.py", line 69, in connect_to_network
    network.connect(network_name)
  File "/Users/ana/Desktop/project/venv/lib/python3.8/site-packages/brownie/network/main.py", line 40, in connect
    web3.connect(host, active.get("timeout", 30))
  File "/Users/ana/Desktop/project/venv/lib/python3.8/site-packages/brownie/network/web3.py", line 54, in connect
    uri = _expand_environment_vars(uri)
  File "/Users/ana/Desktop/project/venv/lib/python3.8/site-packages/brownie/network/web3.py", line 185, in _expand_environment_vars
    raise ValueError(f"Unable to expand environment variable in host setting: '{uri}'")
ValueError: Unable to expand environment variable in host setting: 'https://polygon-mainnet.infura.io/v3/$WEB3_INFURA_PROJECT_ID'`

Do we specify anywhere that users need to get an infura project id and export it? 

export WEB3_INFURA_PROJECT_ID=

**Comment by AnaLoznianu** [comment]
cc @trentmc

**Comment by AnaLoznianu** [comment]
I understand. So it should have used the 'host' parameter. 

But, even if I did all the required steps, I still needed to add this. 
But I think this can be reconciled on this issue: https://github.com/oceanprotocol/ocean.py/issues/1156 as it is addressing the network-config.yaml file. 

Thanks for checking it out 🙏 
cc @mariacarmina
